cache:
  directories:
    - '$HOME/.conan'
    - '$HOME/.pyenv'

matrix:
  - os: osx
    language: objective-c
  - os: linux
    language: cpp

install:
  - |
    pip install --user pipenv urllib3[secure];
    pipenv install --deploy 
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

before_script:
  - |
    if [[ "$CONAN_BUILD" != 1 ]]; then
      pipenv run conan remote add -f bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      pipenv run conan remote add -f libnekit https://api.bintray.com/conan/zhuhaow/libnekit
    fi


script:
  - mkdir build && cd build
  - conan install .. -s cppstd=14 --build
  - cmake ..
  - cmake --build
