image:
  - Visual Studio 2017

configuration:
  - Release

platform:
  - x64

install:
  # Python 3
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%

  - pip install pipenv
  - pipenv install --deploy

before_build:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - pipenv run conan remote add -f bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - pipenv run conan remote add -f libnekit https://api.bintray.com/conan/zhuhaow/libnekit
  - pipenv run conan install . -u -s cppstd=14 --build=missing

build_script:
  - cmake ..
  - cmake --build . --config release

cache:
  - ~/.conan/
